- name: Prepare KVM Virtual machines
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/default.yaml
  pre_tasks:
    - name: check if sudo is passwordless
      debug:
        msg: "It is ok"
      become: true
  roles:
    - terraform-libvirt
  tasks:
    - name: Add DNS host to play
      add_host:
        hostname: dns.essi.labs
        ansible_host: 192.168.131.10
    - name: Add HTTP host to play
      add_host:
        hostname: www.essi.labs
        ansible_host: 192.168.131.10
    - name: Add HAProxy host to play
      add_host:
        hostname: loadbalancer.essi.labs
        ansible_host: 192.168.131.10
- name: Wait for systems
  hosts: "*.essi.labs"
  gather_facts: false
  remote_user: root
  tasks:
    - name: Pausing for systems become ready
      pause:
        seconds: 30

    - name: Systems are ready
      debug:
        msg: Systems are ready

- name: Prepare DNS machine
  import_playbook: deploy_dns.yaml

- name: Prepare WWW machine
  import_playbook: deploy_www.yaml

- name: Prepare HAProxy machine
  import_playbook: deploy_haproxy.yaml

- name: Prepare OpenShift installer
  import_playbook: openshift_installer.yaml
  vars:
    ocp_install_dir: "~/ocp-terraform"
