- name: Deploy DNS machine
  hosts: dns.{{ clusterName }}.{{ baseDomain }}
  remote_user: root
  vars_files:
    - vars/default.yaml
  tasks:
    - name: Register and subscribe
      redhat_subscription:
        username: "{{ rh_user }}"
        auto_attach: yes
        password: "{{ rh_pass }}"
        state: present
      when:
        - ansible_distribution == "RedHat"
        - ( rh_user is defined and rh_pass is defined)

    - name: Install {{ item }}
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - dnsmasq
        - firewalld

    - name: Configure dnsmasq main file
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          local=/{{ clusterName }}.{{ baseDomain }}/
          address=/apps.{{ clusterName }}.{{ baseDomain }}/{{ baseIP }}.10
          address=/ipa.{{ clusterName }}.{{ baseDomain }}/{{ baseIP}}.10
          {% for master in range(1,master_count|int+1) %} 
          srv-host=_etcd-server-ssl._tcp.{{ clusterName }}.{{ baseDomain }},master-{{ master }}.{{ clusterName }}.{{ baseDomain }},2380,0,10

          {% endfor %}
          no-hosts
          addn-hosts=/etc/dnsmasq.openshift.addnhosts
          conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
    - name: get_hosts
      xml: 
        path: /var/run/libvirt/network/openshift-cluster.xml
        xpath: /networkstatus/network/ip/dhcp/host
        content: attribute
      register: xml_net
      delegate_to: localhost
      become: yes

    - name: Configure dnsmasq OCP file
      copy:
        dest: /etc/dnsmasq.openshift.addnhosts
        content: |
          {% set count = namespace(a=0) %}
          {% for machine in xml_net['matches'] %}
          {{ machine['host']['ip'] }} {{ machine['host']['name'] }}.{{ clusterName }}.{{ baseDomain }} {{ machine['host']['name'] }} {% if 'master' in machine['host']['name'] %} etcd-{{ count.a }}.{{ clusterName }}.{{ baseDomain }} etcd-{{ count.a }} {% set count.a = count.a +1 %}{% elif 'dns' in machine['host']['name'] %} api.{{ clusterName }}.{{ baseDomain }} api-int.{{ clusterName }}.{{ baseDomain }} www.{{ clusterName }}.{{ baseDomain }} loadbalancer.{{ clusterName }}.{{ baseDomain }} {% endif %}

          {% endfor %}

    - name: Start and enable {{ item }}
      systemd:
        name: "{{ item }}"
        enabled: true 
        state: started
      loop:
        - dnsmasq
        - firewalld

    - name: Create dnsmasq firewall rule
      firewalld:
        state: enabled
        service: dns
        immediate: true
        permanent: true
