- name: Deploy LoadBlancer machine
  hosts: loadbalancer.essi.labs
  remote_user: root
  vars_files:
    - vars/default.yaml
  vars:
    ports:
      - 80
      - 443
      - 22623
      - 6443
  tasks:
    - name: Register and subscribe
      redhat_subscription:
        username: "{{ rh_user }}"
        auto_attach: yes
        password: "{{ rh_pass }}"
        state: present
      when:
        - ansible_distribution == "RedHat"
        - ( rh_user is defined and rh_pass is defined)

    - name: Install {{ item }} package
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - haproxy
        - firewalld

    - name: Create HAProxy config file
      template:
        dest: /etc/haproxy/haproxy.cfg
        src: files/haproxy.cfg 
        mode: 0644

    - name: Change boolean
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Start and enable {{ item }} service
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - firewalld
        - haproxy

    - name: Open firewall ports
      firewalld:
        state: enabled
        immediate: true
        permanent: true
        port: "{{ item }}/tcp"
      loop: "{{ ports }}"
