- name: Prepare KVM Virtual machines
  hosts: all
  pre_tasks:
    - name: check if sudo is passwordless
      debug:
        msg: "It is ok"
      become: true
  roles:
    - terraform-libvirt

  post_tasks:
    - block:
        - name: get virtual machines
          virt:
            command: list_vms
          register: machines
          become: true

        - name: Add host to play
          add_host:
            hostname: "{{ item }}.{{ network_name }}"
            ansible_host: 10.10.10.1{{ ip_index }}
            group: "demo"
          loop: "{{ machines['list_vms']|select('match','ocp-(bastion|master).*')|list|sort }}"
          loop_control:
            index_var: ip_index

        - name: Add host to play
          add_host:
            hostname: "{{ item }}.{{ network_name }}"
            ansible_host: 10.10.10.2{{ ip_index+1 }}
            group: "demo"
          loop: "{{ machines['list_vms']|select('match','ocp-node.*')|list|sort }}"
          loop_control:
            index_var: ip_index
      when: ssh_key_path is defined

- name: Configure FQDN 
  hosts: demo
  tasks:
    - block:
        - name: disable hostname in NM
          shell: "/usr/bin/nmcli connection add con-name eth0 type ethernet ifname eth0"
          when: inventory_hostname in groups['demo']

        - name: disable hostname in NM
          shell: "/usr/bin/nmcli connection modify eth0 ipv4.dhcp-send-hostname false"
          when: inventory_hostname in groups['demo']

        - name: disable hostname in NM
          shell: "/usr/bin/nmcli connection up eth0"
          when: inventory_hostname in groups['demo']

        - name: set fqdn
          shell: "hostnamectl set-hostname {{ inventory_hostname }}"
          when: inventory_hostname in groups['demo']

        - name: set hostname
          copy:
            dest: /etc/hostname
            content: "{{ inventory_hostname }}"
          become: true
          when: inventory_hostname in groups['demo']
      when: ssh_key_path is defined

    - name: FQDN NOT configured
      debug:
        msg: |
          "Your sistems has not been configured with FQDN.
          You should run 'hostnamectl set-hostname <fqdn-hostname>' on each machine"
      when: ssh_key_path is not defined

