- name: Prepare KVM Virtual machines
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: check if sudo is passwordless
      debug:
        msg: "It is ok"
      become: true
  tasks:
    - name: Add DNS host to play
      add_host:
        hostname: dns.essi.labs
        ansible_host: 192.168.131.10
    - name: Add HTTP host to play
      add_host:
        hostname: www.essi.labs
        ansible_host: 192.168.131.10
    - name: Add HAProxy host to play
      add_host:
        hostname: loadbalancer.essi.labs
        ansible_host: 192.168.131.10

- name: Unsubscribe systems
  hosts: "*.essi.labs"
  gather_facts: true
  remote_user: root
  tasks:
    - name: Unsibscribe
      redhat_subscription:
        state: absent
      when: ansible_distribution == "RedHat"

- name: Destroy systems
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy systems
      import_role:
        name: terraform-libvirt
        tasks_from: destroy
    - name: Destroy openshift-cluster
      virt_net:
        name: openshift-cluster
        state: absent
