- name: Prepare KVM Virtual machines
  hosts: localhost
  gather_facts: false
  vars_files:
    - roles/terraform-libvirt/defaults/main.yml
  pre_tasks:
    - name: check if sudo is passwordless
      debug:
        msg: "It is ok"
      become: true
  tasks:
    - name: get virtual machines
      virt:
        command: list_vms
      register: machines
      become: true

    - name: Add bastion to play
      add_host:
        hostname: "ocp-bastion"
        ansible_host: 10.10.10.10

    - name: Add masters to play
      add_host:
        hostname: "{{ item }}"
        ansible_host: 10.10.10.2{{ ip_index+1 }}
      loop: "{{ machines['list_vms']|select('match','ocp-master.*')|list|sort }}"
      loop_control:
        index_var: ip_index

    - name: Add nodes to play
      add_host:
        hostname: "{{ item }}"
        ansible_host: 10.10.10.4{{ ip_index+1 }}
      loop: "{{ machines['list_vms']|select('match','ocp-node.*')|list|sort }}"
      loop_control:
        index_var: ip_index

- hosts: ocp-*
  tasks:
    - name: check
      ping:

- name: Unsubscribe systems
  hosts: ocp-*
  gather_facts: true
  remote_user: root
  tasks:
    - name: Unsubscribe
      redhat_subscription:
        state: absent
      when: ansible_distribution == "RedHat"

- name: Destroy systems
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy systems
      import_role:
        name: terraform-libvirt
        tasks_from: destroy
    - name: Destroy ocp-network
      virt_net:
        command: "{{ item }}"
        name: "{{ network_name }}"
      loop:
        - destroy
        - undefine
