- name: Prepare KVM Virtual machines
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: check if sudo is passwordless
      debug:
        msg: "It is ok"
      become: true
  tasks:
    - name: get virtual machines
      virt:
        command: list_vms
      register: machines
      become: true
    - name: debug
      debug:
        var: machines['list_vms']|select('match','ocp-master.*')|list

    - name: Add host to play
      add_host:
        hostname: "{{ item }}"
        ansible_host: 10.10.10.1{{ ip_index }}
      loop: "{{ machines['list_vms']|select('match','ocp-(bastion|master).*')|list }}"
      loop_control:
        index_var: ip_index

    - name: Add host to play
      add_host:
        hostname: "{{ item }}"
        ansible_host: 10.10.10.2{{ ip_index+1 }}
      loop: "{{ machines['list_vms']|select('match','ocp-node.*')|list }}"
      loop_control:
        index_var: ip_index

- hosts: ocp-*
  tasks:
    - name: check
      ping:

- name: Unsubscribe systems
  hosts: "10.10.10.*"
  gather_facts: true
  remote_user: root
  tasks:
    - name: Unsibscribe
      redhat_subscription:
        state: absent
      when: ansible_distribution == "RedHat"

- name: Destroy systems
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy systems
      import_role:
        name: terraform-libvirt
        tasks_from: destroy
