- name: Prepare openshift-install
  hosts: www.essi.labs
  gather_facts: false
  remote_user: root

  tasks:
    - name: get release
      uri:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.1/release.txt"
        return_content: true
      register: release

    - name: set version
      set_fact:
        version: "{{ release.content|regex_search('(Name:.*)')|regex_replace('Name:')|trim() }}"

    - name: Create "{{ ocp_install_dir }}"
      file:
        path: "{{ ocp_install_dir }}"
        state: directory

    - name: Download installer
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.1/openshift-install-linux-{{ version }}.tar.gz"
        dest: "{{ ocp_install_dir }}"
        remote_src: true

    - name: Download openshift-client
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.1/openshift-client-linux-{{ version }}.tar.gz"
        dest: /usr/local/bin/
        remote_src: true

    - name: Copy instructions
      copy:
        src: files/Instructions.md
        dest: "{{ ocp_install_dir }}/Instructions.md"
