- name: Prepare openshift-install
  hosts: www.{{ clusterName }}.{{ baseDomain }}
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/default.yaml

  tasks:
    - name: get release
      uri:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-{{ ocp_release }}/release.txt"
        return_content: true
      register: release

    - name: set version
      set_fact:
        version: "{{ release.content|regex_search('(Name:.*)')|regex_replace('Name:')|trim() }}"

    - name: Create "{{ ocp_install_dir }}"
      file:
        path: "{{ ocp_install_dir }}"
        state: directory

    - name: Download installer
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-{{ ocp_release }}/openshift-install-linux-{{ version }}.tar.gz"
        dest: "{{ ocp_install_dir }}"
        remote_src: true

    - name: Download openshift-client
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-{{ ocp_release }}/openshift-client-linux-{{ version }}.tar.gz"
        dest: /usr/local/bin/
        remote_src: true

    - name: Copy instructions
      copy:
        src: files/Instructions.md
        dest: "{{ ocp_install_dir }}/Instructions.md"

    - name: Create install-config.yaml
      copy:
        dest: "{{ ocp_install_dir }}/install-config.yaml"
        content: |
          apiVersion: v1
          baseDomain: {{ baseDomain }}
          compute:
          - hyperthreading: Enabled
            name: worker
            platform: {}
            replicas: 0
          controlPlane:
            hyperthreading: Enabled
            name: master
            platform: {}
            replicas: 3
          metadata:
            creationTimestamp: null
            name: {{ clusterName }}
          networking:
            clusterNetwork:
            - cidr: 10.128.0.0/14
              hostPrefix: 23
            networkType: OpenShiftSDN
            serviceNetwork:
            - 172.30.0.0/16
          platform:
            none: {}
          pullSecret: '{{ lookup('file', pull_secret_path) }}'
          sshKey: '{{ lookup('file', ssh_key_path) }}'

    - name: Create symlink to install-config
      file:
        src: "{{ ocp_install_dir }}/install-config.yaml"
        dest: "{{ ocp_install_dir }}/install-config.yaml.hardlink"
        state: hard
        force: true

    - name: Create ignition files
      shell: |
        cd {{ ocp_install_dir }} && ./openshift-install create ignition-configs
      async: 15
      poll: 5

    - name: list files
      find:
        paths: "{{ ocp_install_dir }}"
        patterns: "*.ign"
      register: ignition_files

    - name: Copy ignition files
      copy:
        remote_src: true
        dest: /var/www/html/ignition
        src: "{{ item.path }}"
      loop: "{{ ignition_files.files }}"

    - name: get hosts
      virt:
        command: list_vms
      register: machines
      delegate_to: localhost
      become: true

    - name: Start machines
      virt:
        command: start
        name: "{{ item }}"
      loop: "{{ machines.list_vms }}"
      when: "'master' in item or 'bootstrap' in item or 'worker' in item"
      become: true
      delegate_to: localhost

    - name: Run bootstrap
      shell: "cd {{ ocp_install_dir }} && ./openshift-install wait-for bootstrap-complete --log-level debug"
      async: 1800
      poll: 0
      register: bootstrap

    - name: Wait for bootstrap for complete
      async_status:
        jid: "{{ bootstrap.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 30




