---
# defaults file for terraform-libvirt
root_pass: redhat
libvirt_packages:
  - bridge-utils 
  - libvirt 
  - libvirt-devel
  - virt-install 
  - qemu-kvm
  - virt-top
  - libguestfs-tools
  - virt-manager
  - python2-lxml
  - python3-lxml
terraform_dir: "~/ocp-terraform"
qcow2_image: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1907.qcow2"
image_found: false
master_count: 3
master_disk: "20G"
worker_count: 1
worker_disk: "20G"
baseDomain: labs
clusterName: essi
ocp_release: "4.6"
ocp_minor: "8"
baseIP: 192.168.131
