apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - dn
        email: 
        - mail
        name: 
        - cn
        preferredUsername: 
        - uid
      bindDN: "uid=admin,cn=users,cn=accounts,dc=aletia,dc=labs" 
      bindPassword: 
        name: ldap-secret
        #ca: 
        #name: ca-config-map
      insecure: true 
      url: "ldap://ipa.aletia.labs/cn=users,cn=accounts,dc=aletia,dc=labs?uid?sub?(uid=*)"
