apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /OCP/registry 
    server: 192.168.131.10
    readOnly: false
