- name: create terraform directory
  file:
    path: "{{ terraform_dir }}"
    state: directory

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ terraform_dir }}/{{ item }}"
  loop:
    - network_config.cfg
    - ocp-lab.tf

- name: copy config data
  template:
    src: cloud_init.cfg.j2
    dest: "{{ terraform_dir }}/cloud_init.cfg"

- name: execute terraform init
  shell: "chdir={{ terraform_dir }} terraform init -get=true -input=false"

- name: execute terraform plan
  shell: "chdir={{ terraform_dir }} terraform plan -out=tfplan -input=false -detailed-exitcode"

- name: execute terraform apply
  shell: "chdir={{ terraform_dir }} terraform -input=false -auto-approve=true tfplan"
