- name: create terraform directory
  file:
    path: "{{ terraform_dir }}"
    state: directory

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ terraform_dir }}/{{ item }}"
  loop:
    - network_config.cfg
    - ocp-lab.tf

- name: copy config data
  template:
    src: cloud_init.cfg.j2
    dest: "{{ terraform_dir }}/cloud_init.cfg"


- name: deploy terraform
  terraform:
    project_path: "{{ terraform_dir }}"
    state: "present"
    force_init: true
