- name: install unzip
  dnf:
    name: unzip
    state: latest
  become: true

- name: download terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: create terraform plugins directory
  file:
    path: ~/.terraform.d/plugins
    state: directory

- name: Confirm /tmp/buildtree directory exists
  file:
    path: /tmp/buildtree
    state: directory
    mode: 1755

- name: Prepare the provider
  git:
    repo: https://github.com/dmacvicar/terraform-provider-libvirt.git
    dest: /tmp/buildtree/terraform-provider-libvirt
    
- name: Build the provider
  make:
    chdir: /tmp/buildtree/terraform-provider-libvirt

- name: Install the provider plugin plugin
  copy:
    remote_src: yes
    src: /tmp/buildtree/terraform-provider-libvirt/terraform-provider-libvirt
    dest: ~/.terraform.d/plugins/
    mode: 0755
