- name: install libvirt packages
  dnf:
    name: "{{ libvirt_packages }}"
    state:  latest
  become: true

- name: start and enable libvirtd daemon
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: configure ocp-net
  virt_net:
    command: define
    name: ocp-net
    xml: '{{ lookup("file", "files/ocp-net.xml") }}'

- name: start ocp-net
  virt_net:
    state: active
    name: ocp-net
