- name: install libvirt packages
  dnf:
    name: "{{ libvirt_packages }}"
    state:  latest
  become: true

- name: start and enable libvirtd daemon
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: "configure {{ item }}"
  virt_net:
    command: define
    name: "{{ item }}"
    xml: '{{ lookup("template", "files/"+item+"-net.xml") }}'
  loop: "{{ ocp_net }}"

- name: start {{ item }}
  virt_net:
    state: active
    name: "{{ item }}"
  loop: "{{ ocp_net }}"
