- name: install libvirt packages
  dnf:
    name: "{{ libvirt_packages }}"
    state:  latest
  become: true

- name: start and enable libvirtd daemon
  systemd:
    name: libvirtd
    enabled: true
    state: started
  become: true

- name: "configure openshift-cluster"
  virt_net:
    command: define
    name: "openshift-cluster"
    xml: '{{ lookup("template", "files/openshift-cluster-net.xml") }}'

- name: start openshift-cluster
  virt_net:
    state: active
    name: "openshift-cluster"
